# Rename this project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'integrichain_poc'
version: '1.0.0'
config-version: 2

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You don't need to change these for this project.
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

# on-run-start and on-run-end are SQL statement(s) or macros that run at the end of 
# dbt run/dbt/seed/dbt snapshot commands. 
# Full documentation: https://docs.getdbt.com/reference/project-configs/on-run-start-on-run-end
on-run-end:
  - "{{ grant_all_on_schemas(schemas, 'public') }}"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this config, we tell dbt how to build the models, where to build them, which warehouse 
# to use, and what query tag to provide on the snowflake site. 
# These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro. 
models:
  integrichain_poc:
    # When you rename the project up top, remember to rename it here too. 
    +materialized: table
    +database: SHREYA_SANDBOX
    +schema: customers
    staging:
          # This defaults every model in the staging directory to be materialized as a view in Snowflake. To learn more about materializations: https://docs.getdbt.com/docs/building-a-dbt-project/building-models/materializations
      +schema: customers
      +snowflake_warehouse: compute_wh
      +tags: "daily"
flags:
  require_generic_test_arguments_property: true
model-paths: ["models"]